Feature/feature branch
RomanNikolaevich/Laravel_Nova_Poshta pull request #1
Opened 2023-02-01 12:30 UTC by RomanNikolaevich

2023-02-01 13:26 UTC, demelianenko-corcentric requested changes

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Controllers/CityController.php
> +        $cities = City::get();
С получением моделей и их изменениями работают только сервисы. Вынести в сервис

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Controllers/WarehouseController.php
> +        $warehouses = Warehouse::get();
Смотри выше про модели

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Services/CityServiceNovaPoshta.php
> +    public function addToDatabase(array $filtered_cities):void
Кэмел кейс, название переменной cities. Принцип единственной ответственности, метод не должен знать какие города к нему прилетают. Они могут быть и не отсортированными

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Services/CityServiceNovaPoshta.php
> +        foreach ($filtered_cities as $city) {
Тут же ты не filteredCity написал же

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Services/CityServiceNovaPoshta.php
> +    public function filterDataFromApi(mixed $cities):void
Какая фиг разница от куда это прилетело. Название filterCities

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Services/CityServiceNovaPoshta.php
> +        $this->addToDatabase($filteredCities);
Возвращает массив городов. А вот это уже вызываешь в контроллере

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Services/CityServiceNovaPoshta.php
> +    private function getFromApi()
Этот метод вызывается из контролера и возвращает  список город. Не отфильтрованных. Далее будешь прокидывать этот список в следующие методы через контроллер

2023-02-01 13:26 UTC, demelianenko-corcentric commented on app/Http/Services/CityServiceNovaPoshta.php
> +        $this->filterDataFromApi($cities);
Возвращаешься список городов отсюда. Этот метод не вызываешь

2023-02-01 13:50 UTC, RomanNikolaevich commented on app/Http/Controllers/CityController.php
> +        $cities = City::get();
+

2023-02-01 13:53 UTC, RomanNikolaevich commented on app/Http/Controllers/WarehouseController.php
> +        $warehouses = Warehouse::get();
+

2023-02-01 13:53 UTC, RomanNikolaevich commented on app/Http/Services/CityServiceNovaPoshta.php
> +    public function addToDatabase(array $filtered_cities):void
+

2023-02-01 13:54 UTC, RomanNikolaevich commented on app/Http/Services/CityServiceNovaPoshta.php
> +        foreach ($filtered_cities as $city) {
+

2023-02-01 13:55 UTC, RomanNikolaevich commented on app/Http/Services/CityServiceNovaPoshta.php
> +    public function filterDataFromApi(mixed $cities):void
Сервис обрабатывает данные из АПИ и из БД. Можно сделать еще один сервис, чтобы он только с БД работал, тогда не нужно писать пояснения в названии сервиса

2023-02-01 15:54 UTC, JokerVDen requested changes

2023-02-01 15:54 UTC, JokerVDen commented on app/Models/Warehouse.php
> +    protected $fillable = ['city_ref', 'description', 'description_ru'];
Сохраняй ref текущей записи вархауса тоже

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/WarehouseService.php
> +            ]);
Вот тут сохраняй реф вархауса тоже

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/CityServiceNovaPoshta.php
> +    public function getFromApi():Collection
getByApi

2023-02-01 15:54 UTC, JokerVDen commented on config/novaposhta.php
> +        "apiKey"       => "",
apiKey один вроде, запихни его в .env и тут вытащи в один из элементов основного массива

2023-02-01 15:54 UTC, JokerVDen commented on config/novaposhta.php
> +        "apiKey"       => "",
Зачем тебе так много apiKey?))
И пройдись везде: нет интерполяции - одинарные кавычки

2023-02-01 15:54 UTC, JokerVDen commented on database/migrations/2023_01_27_153052_create_warehouses_table.php
> +            $table->string('city_ref'); //code of warehous
добавь ref, чтоб сохранять сюда ref что прилетел

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/CityServiceNovaPoshta.php
> +        return Http::post($url, $data)->collect('data');
Если здесь не будет 'data' ключа в массиве, ошибки не будет? Проверь сюда вставь какой нибудь несуществущий ключ

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/CityServiceNovaPoshta.php
> +        $cities = app(CityController::class)->getFromApi();
Вот это вынеси в контроллер, а в этот метод прокидывай параметром эти города. Ещё раз повторяю: В СЕРВИСАХ МЕТОДЫ ТОЛЬКО ДЛЯ ОБРАБОТКИ ДАННЫХ ИЗ ПАРАМЕТРОВ, никаких вызовов контроллеров!

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/CityServiceNovaPoshta.php
> +    public function filterDataFromApi():array
просто filterCities, этот метод ничего не должен знать про API вообще

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/CityServiceNovaPoshta.php
> +        foreach ($limitCities as $city) {
Заюзай вот это здесь https://laravel.com/docs/9.x/collections#method-filter, и верни коллекцию из метода

2023-02-01 15:54 UTC, JokerVDen commented on app/Services/CityServiceNovaPoshta.php
> +        $cities = app(CityController::class)->getFilteredDataFromApi();
Ещё раз!!!!! Не делай так!!!!! В метод параметом прилетают города! А вот этот код в контроллер вынеси, и из контроллера уже вызывай этот метод с уже готовыми городами как параметр

2023-02-01 15:57 UTC, RomanNikolaevich commented on app/Services/CityServiceNovaPoshta.php
> +    public function getFromApi():Collection
+

2023-02-01 16:01 UTC, RomanNikolaevich commented on app/Services/CityServiceNovaPoshta.php
> +        return Http::post($url, $data)->collect('data');
там в коллекции много разных массивов, мне нужен только этот - он называется data

2023-02-01 16:21 UTC, RomanNikolaevich commented on app/Models/Warehouse.php
> +    protected $fillable = ['city_ref', 'description', 'description_ru'];
+

2023-02-01 16:22 UTC, RomanNikolaevich commented on app/Services/WarehouseService.php
> +            ]);
+

2023-02-01 16:22 UTC, RomanNikolaevich commented on app/Services/CityServiceNovaPoshta.php
> +    public function getFromApi():Collection
+

2023-02-01 16:50 UTC, RomanNikolaevich commented on config/novaposhta.php
> +        "apiKey"       => "",
+

2023-02-01 16:52 UTC, RomanNikolaevich commented on config/novaposhta.php
> +        "apiKey"       => "",
+

2023-02-01 19:10 UTC, RomanNikolaevich commented on app/Services/CityServiceNovaPoshta.php
> +        return Http::post($url, $data)->collect('data');
пустой массив возвращает, если изменить вместо data на другое название ключа

2023-02-02 14:38 UTC, JokerVDen requested changes

2023-02-02 14:38 UTC, JokerVDen commented on app/Services/CityNovaPoshtaService.php
> +        foreach ($cities->toArray() as $city) {
Вроде не нужно тут преобразовывать в массив, проверь это. Должно без этого работать

2023-02-02 14:38 UTC, JokerVDen commented on app/Services/WarehouseNovaPoshtaService.php
> +        foreach ($warehouses as $warehouse) {
Тут же работает))

2023-02-02 14:39 UTC, JokerVDen commented on app/Http/Controllers/WarehouseController.php
> +        $cities = app(CityController::class)->getFromDB();
Контроллер контроллер не должен вызывать. Тут заюзай сервис лучше чужой

2023-02-02 14:43 UTC, JokerVDen requested changes

2023-02-02 14:43 UTC, JokerVDen commented on app/Services/WarehouseNovaPoshtaService.php
> +    public function filtered(Collection $warehouses, $cities):Collection
Вот тут city не подсветил

2023-02-02 15:33 UTC, JokerVDen approved these changes

2023-02-02 19:20 UTC, merged